language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - "pip install coverage pylint"
  - "pip install -r requirements.txt"
  - "pip install ."
# command to run before tests
before_script:
  - "python -m compileall ."
# command to run tests
script:
  - "python manage.py check"
  - "coverage run manage.py test"
# command to run after tests
after_script:
  - "coverage report -m"
  - "pylint --py3k hcalendar"
