language: python
python:
  - "3.5"
  - "3.6"
services:
  - redis-server
# command to install dependencies
install:
  - "pip install coverage pylint"
  - "pip install -r requirements.txt"
# command to run before tests
before_script:
  - "python -m compileall ."
  - "python manage.py check"
# command to run tests
script:
  - "coverage run manage.py test"
# command to run after tests
after_script:
  - "coverage report -m"
  - "pylint webgcal"
