application: webgcal
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /media
  static_dir: _generated_media

- url: /cron/.*
  script: djangoappengine/main/main.py
  login: admin

- url: /taskqueue/.*
  script: djangoappengine/main/main.py
  login: admin

- url: /.*
  script: djangoappengine/main/main.py
  secure: always
