migrate:
  build: .
  links:
   - db
   - redis
  volumes:
   - .:/usr/src/app
  command: /usr/src/env/bin/python manage.py migrate
loaddata:
  build: .
  links:
   - db
   - redis
  volumes:
   - .:/usr/src/app
  command: /usr/src/env/bin/python manage.py loaddata docker-fixture.json
web:
  build: .
  links:
   - db
   - redis
   - migrate
   - loaddata
  ports:
   - "8000:8000"
  volumes:
   - .:/usr/src/app
  command: /usr/src/env/bin/python manage.py runserver 0.0.0.0:8000
dragon:
  build: .
  links:
   - db
   - redis
   - web
  ports:
   - "9999:9999"
  volumes:
   - .:/usr/src/app
  command: /usr/src/env/bin/python manage.py runsd 0.0.0.0:9999
celery:
  build: .
  links:
   - db
   - redis
   - web
  volumes:
   - .:/usr/src/app
  command: /usr/src/env/bin/python manage.py celeryd -B -E -c 2
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: docker
    MYSQL_DATABASE: docker
    MYSQL_USER: docker
    MYSQL_PASSWORD: docker
redis:
  image: redis
phpmyadmin:
  image: maxexcloo/phpmyadmin
  links:
   - db:mariadb
  ports:
   - "8080:80"
