web:
  image: mback2k/django-webgcal
  links:
   - db
   - redis
  ports:
   - "8000:8000"
  volumes:
   - .:/app
  environment:
    DJANGO_PERFORM_SETUP: "yes"
celery_worker:
  image: mback2k/django-webgcal
  links:
   - db
   - redis
  volumes:
   - .:/app
  environment:
    DJANGO_PERFORM_SETUP: "no"
  command: /usr/local/bin/celery worker -A webgcal -E -c 2 -l info
celery_beat:
  image: mback2k/django-webgcal
  links:
   - db
   - redis
  volumes:
   - .:/app
  environment:
    DJANGO_PERFORM_SETUP: "no"
  command: /usr/local/bin/celery beat -A webgcal -S django -l info
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: docker
    MYSQL_DATABASE: docker
    MYSQL_USER: docker
    MYSQL_PASSWORD: docker
redis:
  image: redis
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
   - PMA_ARBITRARY=1
  links:
   - db:mariadb
  ports:
   - "8080:8080"
